@isTest
global class RecordsTest
{
    private static testMethod void all()
    {
        System.assert( false, 'implement test' );
    }

    private static testMethod void none()
    {
        System.assert( false, 'implement test' );
    }

    private static testMethod void both()
    {
        System.assert( false, 'implement test' );
    }

    private static testMethod void all_conjunction()
    {
        System.assert( false, 'implement test' );
    }

    private static testMethod void either()
    {
        System.assert( false, 'implement test' );
    }

    private static testMethod void any()
    {
        System.assert( false, 'implement test' );
    }
}
